/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { JobApplicationService } from "../jobApplication.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JobApplicationCreateInput } from "./JobApplicationCreateInput";
import { JobApplication } from "./JobApplication";
import { JobApplicationFindManyArgs } from "./JobApplicationFindManyArgs";
import { JobApplicationWhereUniqueInput } from "./JobApplicationWhereUniqueInput";
import { JobApplicationUpdateInput } from "./JobApplicationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class JobApplicationControllerBase {
  constructor(
    protected readonly service: JobApplicationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JobApplication })
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createJobApplication(
    @common.Body() data: JobApplicationCreateInput
  ): Promise<JobApplication> {
    return await this.service.createJobApplication({
      data: data,
      select: {
        company: true,
        createdAt: true,
        dateApplied: true,
        datePosted: true,
        dateSaved: true,
        followUp: true,
        id: true,
        jobPosition: true,
        location: true,
        maxSalary: true,
        minSalary: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [JobApplication] })
  @ApiNestedQuery(JobApplicationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobApplications(
    @common.Req() request: Request
  ): Promise<JobApplication[]> {
    const args = plainToClass(JobApplicationFindManyArgs, request.query);
    return this.service.jobApplications({
      ...args,
      select: {
        company: true,
        createdAt: true,
        dateApplied: true,
        datePosted: true,
        dateSaved: true,
        followUp: true,
        id: true,
        jobPosition: true,
        location: true,
        maxSalary: true,
        minSalary: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JobApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobApplication(
    @common.Param() params: JobApplicationWhereUniqueInput
  ): Promise<JobApplication | null> {
    const result = await this.service.jobApplication({
      where: params,
      select: {
        company: true,
        createdAt: true,
        dateApplied: true,
        datePosted: true,
        dateSaved: true,
        followUp: true,
        id: true,
        jobPosition: true,
        location: true,
        maxSalary: true,
        minSalary: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JobApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateJobApplication(
    @common.Param() params: JobApplicationWhereUniqueInput,
    @common.Body() data: JobApplicationUpdateInput
  ): Promise<JobApplication | null> {
    try {
      return await this.service.updateJobApplication({
        where: params,
        data: data,
        select: {
          company: true,
          createdAt: true,
          dateApplied: true,
          datePosted: true,
          dateSaved: true,
          followUp: true,
          id: true,
          jobPosition: true,
          location: true,
          maxSalary: true,
          minSalary: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JobApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteJobApplication(
    @common.Param() params: JobApplicationWhereUniqueInput
  ): Promise<JobApplication | null> {
    try {
      return await this.service.deleteJobApplication({
        where: params,
        select: {
          company: true,
          createdAt: true,
          dateApplied: true,
          datePosted: true,
          dateSaved: true,
          followUp: true,
          id: true,
          jobPosition: true,
          location: true,
          maxSalary: true,
          minSalary: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
